### PR TITLE
Add support for IsSellerImporterOfRecord parameter in Avalara API

### PR DESCRIPTION
**Pull request by rsisco**

### CODE REVIEW

**Comment by erikhansen** [comment]
@ted-spence-avalara Thanks for merging this. We're making [an update](https://github.com/classyllama/ClassyLlama_AvaTax/pull/64) to the Magento 2 AvaTax extension that depends on these changes. Can you tag a new 15.5.2 release in Github so that the Packagist page (https://packagist.org/packages/avalara/avatax) gets updated with the new version?

We'll need that to happen before we can push out the Magento 2 update.

**Comment by erikhansen** [comment]
@ted-spence-avalara Would you be able to tag a 1.15.2 release? You can do that by going to the https://github.com/avadev/AvaTax-Calc-SOAP-PHP/releases page and click the "Draft a new release" button. Having a 1.15.2 release tagged is necessary for us to be able to merge in [this PR](https://github.com/classyllama/ClassyLlama_AvaTax/pull/64) to the Magento 2 AvaTax extension.

**Review by vijaynalawade-avalara — COMMENTED** [review]
Changes look good.

**Comment by erikhansen** [comment]
@ted-spence-avalara Thanks for tagging a new release. However it looks like there are a couple of things preventing me from targeting the release in the AvaTax Magento 2 extension. Can you resolve the following two things:

1. The [composer.json file](https://github.com/avadev/AvaTax-Calc-SOAP-PHP/blob/master/composer.json#L3) declares the module version to be 1.15.2, but the release version you tagged is 1.15.1.1. Can you rectify this?

2. The https://packagist.org/packages/avalara/avatax page has not been updated with the latest 1.5.1.1 release. I'm pretty sure that when Anya setup the Packagist page, she configured this Github repo to push updates to Packagist, but that might need to be setup again.

**Comment by erikhansen** [comment]
@ted-spence-avalara [Packagist still has not updated](https://packagist.org/packages/avalara/avatax) to acknowledge the existing of version 1.15.2 of this extension. Can you try to setup the Github hook that's mentioned here: https://packagist.org/about#how-to-update-packages

**Pull request merged**
